kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-conf
  labels:
    app: proxy
data: 
  default.conf: |
    server {
        listen 8888;
        location / {
            resolver 8.8.8.8;
            proxy_pass http://$http_host$uri$is_args$args;
        }
    }
  default: |
    server {
        listen 8888;
        location / {
            resolver 8.8.8.8;
            proxy_pass http://$http_host$uri$is_args$args;
        }
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      name: proxy
      labels:
        app: proxy
    spec:
      nodeSelector:
        egress: "true" # Solo en el nodo seleccionado como egreso
      containers:
        - name: proxy
          image: nginx
          ports: 
            - containerPort: 8888
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              readOnly: true
              name: proxy-conf
      volumes:
        - name: proxy-conf
          configMap: 
            name: proxy-conf
            items:
              - key: default.conf
                path: default.conf 
---
kind: Service
apiVersion: v1
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  type: ClusterIP
  ports: 
    - port: 8888
  selector:
    app: proxy
